config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :incomes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "expenses#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
    @expense = Expense.new
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    #@expense.lenders.build
    @lender = Lender.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    if params[:expense][:new_lender].present?
      lender = Lender.find_or_create_by(name: params[:expense][:new_lender])
      @expense.lender = lender
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:expense_name, :lender, :category, :new_lender)
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
  
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:expense_name, :value, :date, :extra, :category_name, :currency_name, :new_lender,
        lender_attributes: [:first_name, :last_name, :number_acount, :_destroy]
        )
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Expense name:</strong>
    <%= expense.expense_name %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= expense.value %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= expense.date %>
  </p>

  <p>
    <strong>Extra:</strong>
    <%= expense.extra %>
  </p>

  <p>
    <strong>Lender:</strong>
    <%= expense.lender_id %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= expense.category_name %>
  </p>

  <p>
    <strong>Currency:</strong>
    <%= expense.currency_name %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense, data: { controller: "nested-form", nested_form_wrapper_selector_value: '.nested-form-wrapper'}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :expense_name %>
    <%= f.input :value %>
    <%= f.input :date %>
    <%= f.input :extra %>
    <%= f.association :lender, collection: Lender.all.order(:first_name), label_method: :name, value_method: :id, include_blank: true %>

    <template data-nested-form-target="template">
    <%= f.fields_for :lender, Lender.new, child_index: 'NEW_RECORD' do |lender_fields| %>
      <%= render "lenders/form", f: lender_fields %>
    <% end %>

    </template>
    <%= f.fields_for :lender do |lender_fields| %>
      <%= render "lenders/form", f: lender_fields %>
    <% end %>
    <!-- Inserted elements will be injected before that target. -->
    <div data-nested-form-target="target"></div>
    <button type="button" data-action="nested-form#add" data-turbo-frame="lenders_form">Add lender</button>
    <%= f.submit %>

    <%= f.association :category %>
    <%= f.association :currency %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to "Back", expenses_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<main class = "col-lg-10 mx-auto mt-5">
  <div class = "row mt-4 mb-4">
    <%= turbo_frame_tag 'expense_controller' do %>
      <h1>Expenses</h1>
      <div id="expenses">
        <% @expenses.each do |expense| %>
          <%= render "form", expense: @expense %>
          <p>
            <%= link_to "Show this expense", expense %>
          </p>
        <% end %>
      </div>
      <button type = "button" class="btn btn-primary">
        <%= link_to "New expense", new_expense_path, :class => "btn"%>
      </button>
    <% end %>
  </div>
</main>

app/views/expenses/new.html.erb
<%= turbo_frame_tag 'expense_controller' do %>
  <div class="col-lg-8 mx-auto">
  <div class = "row mt-4 mb-4">
    <div class="card shadow">
      <div class="card-header">
        <h1 class="card-title">New expense</h1>
      </div>
      <div class="card-body">
        <%= render "form", expense: @expense %>
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>